global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-api'
    static_configs:
      - targets: ['node-api:3000']

  - job_name: 'go-api'
    static_configs:
      - targets: ['go-api:50051']
